language: openscad

matrix:
  include:
    - os: linux
      env: TARGET="linux"

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file_glob: true
  file: build/*.stl
  skip_cleanup: true

branches:
  only:
    - master

install:
  - apt-get install openscad

script:
  - sh build.sh
